const blankLine = ' | | ';
console.log("This is what a blank board would look like.");
console.log(blankLine);
console.log(blankLine);
console.log(blankLine);
const guessLine = '1| | ';
const bombLine = ' |B| ';
console.log("This is what a board with a bomb and a guess would look like:");
console.log(guessLine);
console.log(bombLine);
console.log(blankLine);
